### ISSUE TITLE
200/OK code is returned when an error is thrown.

### ISSUE THREAD

**Issue by tayloa45** [apigee-127/magic#13]
This happens when I throw an error in my code. This:

    throw 'An error has occurred';

results in a 503, but this:

    throw { "message": "An error has occurred" };

results in a 200/OK message.

I don't know if A127 is using errors to send non-error data or if this is just a glitch, but in either case, an exception should surely result in a 5xx response?

It is a particular problem because the Volos cache module throws errors of exactly this form, resulting in our users getting 200/OK messages when actually the server has errored.

**Comment by theganyo** [comment]
Hey Andrew. Thanks for your report!

To be honest, I've never seen anyone throw a non-error (ie. string or object) before. While you certainly can, I think that would be an anti-pattern and might potentially cause errors in many places. I'd recommend sticking to the more standard pattern of throwing errors like this to avoid such issues:

```
throw new Error('An error has occurred');
```

**Comment by tayloa45** [comment]
I appreciate it's bad practice, but this error is being thrown by the Volos cache module that comes with A127, so it's not really in my power to change it.

**Comment by theganyo** [comment]
If that's the case, it should be changed. Please give me a pointer to the code in question. I have not found any place this happens.

**Comment by theganyo** [comment]
I'm closing this for now. If you find a place where this is happening, please reopen and let me know. Thanks!
