### ISSUE TITLE
Stack trace is shown as validation fails for request parameters

### ISSUE THREAD

**Issue by hjpbarcelos** [apigee-127/magic#4]
Whenever a request has invalid parameters, a127 middleware automatically stops the request flow and send back a response like this:

> Error: Parameter (body) is not a valid SomeModel model
... stack trace

We should be able to suppress this stack trace, at least for the production environment.

I could not found any docs on this issue, neither by inspecting the source code.

**Comment by theganyo** [comment]
I'm closing this as the official solution is to address it using a handler as mentioned above. If this doesn't solve your issue, please let me know.
