### ISSUE TITLE
support array of controller paths in config files (default.yaml)

### ISSUE THREAD

**Issue by borisirota** [apigee-127/magic#7]
Hi,

The swagger router middleware accepts array of controller paths ([#19](https://github.com/apigee-127/swagger-tools/issues/19)), but the magic module doesn't support this option as a configuration option to the user (support only one path as string).

As can be seen [here](https://github.com/apigee-127/magic/blob/master/lib/middleware.js#L43), behind the scenes it actually passing array of paths but it expects the 'magic.controllers.controllers' to be a string and when passing an array an exception is thrown.

To make it work, it requires 2 changes:
1. replace [this line](https://github.com/apigee-127/magic/blob/master/lib/middleware.js#L43) with:

``` javascript
  if (mainControllers) { 
    if (_.isString(magic.controllers.controllers)) {
        controllers.push(mainControllers);
    } else if (_.isArray(magic.controllers.controllers)) {
        controllers = controllers.concat(mainControllers);
    }
  }
```

and add `var _ = require('underscore');` at the top  
2. add after [this if statement](https://github.com/apigee-127/magic/blob/master/lib/config.js#L107):

``` javascript
  } else if (_.isArray(magic.controllers.controllers)) {
    magic.controllers.controllers = _.map(magic.controllers.controllers, function (_path) {
        return path.resolve(appRoot, _path);
    })
  }
```

Please support this. I have 2 use cases for that and it will make my life a little bit easier :)

Thanks,
Boris.

**Comment by borisirota** [comment]
Sure. I'm about to implement this in the following days (when I'll have some time).
I can implement it, check it with my own project and then send it to you.
Is it ok (my first time in an open source project so feel free :) ) ? Any special requests or ideas?

**Comment by borisirota** [comment]
@theganyo You are welcome to take a look at the implementation of this module.
I tried to make it as similar as possible to yours volos providers and the volos-swagger module.
Its not finished, more providers should be added and it should be tested more seriously but for basic skeleton its enough I think.

[volos-oauth-social](https://github.com/borisirota/volos-oauth-social)
[swagger-volos-oauth-social](https://github.com/borisirota/swagger-volos-oauth-social)  

It will be great to hear your thoughts :)

Boris

**Comment by theganyo** [comment]
This is looking good!

**Comment by borisirota** [comment]
:)
